### ISSUE TITLE
ruby v3.0 error

### ISSUE THREAD

**Issue by MortenTh** [QuickPay/quickpay-ruby-client#47]
When trying to use the client with a newer ruby version it cause an error
gems/quickpay-ruby-client-3.0.2/lib/quickpay/api/client.rb:33:in `block (2 levels) in <class:Client>': wrong number of arguments (given 2, expected 1) (ArgumentError)

This seems to be an issue related to ruby version being higher. https://stackoverflow.com/questions/65469682/argumenterror-wrong-number-of-arguments-given-2-expected-1-after-updating-t

**Comment by gnulinooks** [comment]
Things are looking fine.
Tested it on Mailer, upgraded the of quickpay-ruby-client to 3.0.2
Ruby version inside the container is 3.2, which is right as we mentioned it in Dockerfile. It was the stable newest at the time of creation of this issue.
![image](https://github.com/QuickPay/quickpay-ruby-client/assets/68404/836dc823-dece-4c3a-8d97-fb9ee881216f)

api/qapi-backend also uses quickpay-ruby-client 3.0.2 and vagrant has 2.7 ruby. Which is also working fine with it.

Though ticket says Ruby 3.0, but most of our dockrized projects are 3.0+ and in vagrant it is 2.7

Will stop working on this and keep it open for some time.

@MortenTh , which repo were you working with if you remember?

**Comment by MortenTh** [comment]
@gnulinooks Cant remember sadly but I also ran a script with the ruby client yesterday without issues on ruby 3.0.2 but I'll reopen issue if it happens again so feel free to close it if you cannot find anything.

**Comment by gnulinooks** [comment]
Thank you for the confirmation.

Closing it.
