### ISSUE TITLE
Couldn't bundle nor install quickpay-ruby-client gem

### ISSUE THREAD

**Issue by SimonPotier** [QuickPay/quickpay-ruby-client#9]
Hello,
I can't manage to install quickpay gem.
In my Gemfile : 

gem 'quickpay-ruby-client'
I get "Could not find gem 'quickpay-ruby-client (>= 0) ruby' in the gems available on this machine."

direct git try : 
gem 'quickpay-ruby-client', :git => 'https://github.com/QuickPay/quickpay-ruby-client.git' 
this bundle correctly but the gem isn't installed in my project (uninitialized constant QuickPay in rails console).

direct install in rails project : 
gem install quickpay-ruby-client
this return "Could not find a valid gem 'quickpay-ruby-client' (>= 0) in any repository"

Any solutions ? 
Thanks for reading.

**Comment by ta** [comment]
Sorry, this code is not yet available as gem just yet. We hope to get to that within the next few days.

Meanwhile, try `require "quickpay"` in your console to load the code. I'm closing this issue - feel free to reopen if you have more questions.

**Comment by ta** [comment]
@simm19: The client is now released as a gem: https://rubygems.org/gems/quickpay-ruby-client
